version: '3'

networks:
  rails:
    driver: bridge

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    networks:
      - rails
    environment:
      RABBITMQ_VHOST: "/"
      RABBITMQ_NODE_NAME: rabbit@localhost
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
  worker:
    build: .
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'rabbitmq'
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    restart: always
    image: 'worker'
    networks:
      - rails
  bert-server:
    image: bert
    build: ./bert
    networks:
      - rails
    ports:
      - "8125:8125"
    restart: on-failure